ARG PM2_VERSION=5.3.1
ARG NODE_VERSION=22.3.0
ARG ALPINE_VERSION=3.19.1
ARG BUN_VERSION=1.1.14

FROM node:${NODE_VERSION}-slim AS build

WORKDIR /app

RUN apt update; \
  apt install -y openssl

# Install Bun in the specified version
ARG BUN_VERSION
RUN npm install -g bun@${BUN_VERSION}

# Install pm2
RUN npm i -g pm2@${PM2_VERSION}

ENV NODE_ENV=development

# CMD is in compose file
