version: '3.7'

services:
  dbbackup:
    build:
      context: ./containers/dbbackup/
      args:
        - HOST_USER_ID
        - HOST_GROUP_ID
    env_file:
      - ./config/mysql.local.env
    volumes:
      - ../persistent-data/mariadb/:/mysqlfiles/:rw
      - ../persistent-data/backup/:/backup/:rw
      - ./containers/dbbackup/mysql-errors:/mysql-errors:rw
    links:
      - db:db
    restart: always
